import { useState, useEffect } from 'react';
import { getProducts, getForecast } from '../services/api';
import type { Product, Forecast } from '../services/api';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { TrendingUp, Package } from 'lucide-react';

const DemandForecast = () => {
  const [products, setProducts] = useState<Product[]>([]);
  const [selectedProduct, setSelectedProduct] = useState<string>('');
  const [forecast, setForecast] = useState<Forecast | null>(null);

  useEffect(() => {
    getProducts().then(res => {
      setProducts(res.data);
      if (res.data.length > 0) {
        setSelectedProduct(res.data[0].product_id);
      }
    });
  }, []);

  useEffect(() => {
    if (selectedProduct) {
      getForecast(selectedProduct, 14).then(res => setForecast(res.data));
    }
  }, [selectedProduct]);

  const chartData = forecast?.forecast.map((val, idx) => ({
    day: `Day ${idx + 1}`,
    PredictedDemand: val
  })) || [];

  return (
    <div className="p-8 h-full flex flex-col">
      <div className="flex justify-between items-center mb-8">
        <h1 className="text-3xl font-bold text-white flex items-center gap-3">
          <TrendingUp className="text-primary w-8 h-8" />
          ML Demand Forecasting
        </h1>
        
        <div className="w-72">
          <select 
            value={selectedProduct}
            onChange={(e) => setSelectedProduct(e.target.value)}
            className="w-full bg-surface border border-gray-700 rounded-lg px-4 py-2 text-white focus:outline-none focus:border-primary"
          >
            {products.map(p => (
              <option key={p.product_id} value={p.product_id}>
                {p.product_name}
              </option>
            ))}
          </select>
        </div>
      </div>

      {forecast && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 flex-1">
          <div className="lg:col-span-2 bg-surface rounded-xl border border-gray-800 p-6 flex flex-col shadow-lg">
            <h2 className="text-xl font-bold mb-6 text-white">14-Day Horizon Prediction</h2>
            <div className="flex-1 min-h-[400px]">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={chartData} margin={{ top: 20, right: 30, left: 20, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#374151" />
                  <XAxis dataKey="day" stroke="#9ca3af" />
                  <YAxis stroke="#9ca3af" />
                  <Tooltip 
                    contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #374151', color: '#fff' }}
                  />
                  <Legend />
                  <Line 
                    type="monotone" 
                    dataKey="PredictedDemand" 
                    name="Predicted Demand (Units)" 
                    stroke="#3b82f6" 
                    strokeWidth={3}
                    activeDot={{ r: 8 }} 
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="flex flex-col gap-6">
            <div className="bg-surface rounded-xl border border-gray-800 p-6 shadow-lg">
              <h3 className="text-gray-400 font-medium mb-1">Total Predicted Demand (14 Days)</h3>
              <p className="text-4xl font-bold text-white">{forecast.total_predicted_demand.toFixed(1)} <span className="text-lg text-gray-500 font-normal">units</span></p>
            </div>

            <div className="bg-surface rounded-xl border border-gray-800 p-6 shadow-lg">
              <h3 className="text-gray-400 font-medium mb-1">Average Daily Demand</h3>
              <p className="text-4xl font-bold text-primary">{forecast.average_daily_demand.toFixed(2)} <span className="text-lg text-gray-500 font-normal">units/day</span></p>
            </div>

            <div className="bg-surface rounded-xl border border-gray-800 p-6 shadow-lg flex-1">
               <h3 className="text-gray-400 font-medium mb-4 flex items-center gap-2">
                 <Package className="w-5 h-5 text-gray-400"/> Inventory Context
               </h3>
               <p className="text-sm text-gray-300">
                 These predictions are generated by the <strong>Gradient Boosting Regressor</strong>, trained chronologically to avoid look-ahead bias. 
                 The model leverages 30-day rolling moving averages, day-of-week seasonality, and momentum indicators.
               </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default DemandForecast;
